version: "3.9"

services:
  site:
    build:
      dockerfile: site/dev.Dockerfile
    stop_grace_period: 1s
    restart: unless-stopped
    ports:
      - "3000"
    labels:
      traefik.enable: true
      traefik.http.routers.mcieno/marketchef/site.rule: Host(`marketchef.mcieno.internal`)
      traefik.http.routers.mcieno/marketchef/site.tls: true
    working_dir: /site
    command: npm run dev
    volumes:
      - ./site:/site
    environment:
      OBSERVABLE_TELEMETRY_DISABLE: true
      SENTRY_RELEASE: SNAPSHOT
      SENTRY_ENVIRONMENT: local
      SENTRY_PUBLIC_KEY: ${SENTRY_PUBLIC_KEY:-example}

  functions:
    build:
      dockerfile: site/dev.Dockerfile
    stop_grace_period: 1s
    restart: unless-stopped
    ports:
      - "8787"
    labels:
      traefik.enable: true
      traefik.http.routers.mcieno/marketchef/functions.rule: Host(`marketchef.mcieno.internal`) && PathPrefix(`/api/`)
      traefik.http.routers.mcieno/marketchef/functions.tls: true
    working_dir: /site
    command: npx wrangler pages dev --ip 0.0.0.0 --port 8787 .
    volumes:
      - ./site:/site
    environment:
      SENTRY_RELEASE: SNAPSHOT
      SENTRY_ENVIRONMENT: local
